name: air2money
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  image_picker: ^1.0.5
  shared_preferences: ^2.2.2
  go_router: ^12.1.1
  provider: ^6.0.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/logos.jpg"

flutter:

  uses-material-design: true
  assets:
    - lib/assets/
